services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_ROOT_PASSWORD=example'
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
  boost-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - 'DATA_BASE_HOST=mysql'
    ports:
      - '8080:8080'